services:
  - type: web
    name: VipSite
    env: python
    python: "3.10.12"
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "gunicorn --worker-class eventlet -w 1 app:app"
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.12"
